name: Upload Latest Artifact to Release

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download Latest Artifact
        run: |
          # Fetch the latest artifact URL
          artifact_url=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r '.artifacts[0].archive_download_url')

          # Download the latest artifact
          curl -L -o ProchaineStation.zip -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$artifact_url"

      - name: Get Latest Release ID
        id: get_release_id
        run: |
          release_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.id')

          echo "::set-output name=release_id::$release_id"

      - name: Get Latest Tag Name
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=latest_tag::$latest_tag"
      
      - name: Delete Old Release Assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.get_latest_tag.outputs.latest_tag }}
          assets: '*'

      - name: Get Latest Release Upload URL
        id: get_release_upload_url
        run: |
          release_upload_url=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.upload_url')

          echo "::set-output name=release_upload_url::$release_upload_url"

      - name: Upload Artifact to Release
        if: steps.get_release_upload_url.outputs.release_upload_url != null
        run: |
          release_upload_url=$(echo "${{ steps.get_release_upload_url.outputs.release_upload_url }}" | sed 's/{?name,label}//')

          # Upload the artifact to the release
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" \
          --data-binary "@ProchaineStation.zip" "$release_upload_url?name=ProchaineStation.zip"
