name: Upload Latest Artifact to Release

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download Latest Artifact
        run: |
          # Fetch the latest artifact URL
          artifact_url=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r '.artifacts[0].archive_download_url')

          # Download the latest artifact
          curl -L -o ProchaineStation.zip -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$artifact_url"

      - name: Get Latest Release Info
        id: get_release
        run: |
          release_url=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.url')

          echo "::set-output name=release_url::$release_url"

      - name: Get Existing Assets
        id: get_assets
        if: steps.get_release.outputs.release_url != null
        run: |
          assets_url=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "${{ steps.get_release.outputs.release_url }}/assets" | jq -r '.[].url')

          echo "::set-output name=assets_url::$assets_url"

      - name: Delete Existing Assets
        if: steps.get_assets.outputs.assets_url != null
        run: |
          assets_url="${{ steps.get_assets.outputs.assets_url }}"

          while IFS= read -r asset_url; do
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$asset_url"
          done <<< "$assets_url"

      - name: Get Latest Release Upload URL
        id: get_release_upload_url
        run: |
          release_upload_url=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.upload_url')

          echo "::set-output name=release_upload_url::$release_upload_url"

      - name: Upload Artifact to Release
        if: steps.get_release_upload_url.outputs.release_upload_url != null
        run: |
          release_upload_url=$(echo "${{ steps.get_release_upload_url.outputs.release_upload_url }}" | sed 's/{?name,label}//')

          # Upload the artifact to the release
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" \
          --data-binary "@ProchaineStation.zip" "$release_upload_url?name=ProchaineStation.zip"
